-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓

-- ┃                    Decorations Configuration                ┃

-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
local mocha = require("themes.catppuccin.mocha")

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
    decoration = {
        active_opacity = 1,
        rounding = 4,
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            size = 15,
            passes = 2,
            -- more passes = more resource intensive.
            xray = true,
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#shadow
        shadow = {
            enabled = false,
        },
    },
})
